website/auth.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from .models import User, Question, Category, Answer
from werkzeug.security import generate_password_hash, check_password_hash
from . import db
from flask_login import login_user, login_required, logout_user, current_user


auth = Blueprint('auth', __name__)


@auth.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        email = request.form.get('email')
        password = request.form.get('password')

        user = User.query.filter_by(email=email).first()
        if user:
            if check_password_hash(user.password, password):
                flash('Logged in successfully!', category='success')
                login_user(user, remember=True)
                return redirect(url_for('views.home'))
            else:
                flash('Incorrect password, try again.', category='error')
        else:
            flash('Email does not exist.', category='error')
    return render_template("login.html", user=current_user)

@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth.login'))
    

@auth.route('/signup', methods=['GET', 'POST'])
def signup():
    if request.method == 'POST':
        username = request.form.get('Username')
        email = request.form.get('email')
        password1 = request.form.get('password1')
        password2 = request.form.get('password2')

        user = User.query.filter_by(email=email).first()
        if user:
            flash('Email already exists', category='error')
        elif len(email) < 4:
            flash('Email must be greater than 3 characters', category='error')
        elif len(username) < 2:
            flash('Username must be greater than 1 character', category='error')
        elif password1 != password2:
            flash('Passwords don\'t match', category='error')
        elif len(password1) < 7:
            flash('Password must be at least 7 characters', category='error')
        else:
            new_user = User(email=email, username=username, password=generate_password_hash(password1, method='sha256'))
            db.session.add(new_user)
            db.session.commit()
            login_user(new_user, remember=True)
            flash('Account created!', category='success')
            return redirect(url_for('views.home'))

    return render_template("sign_up.html", user=current_user)


@auth.route('/search' , methods=['POST'])
@login_required
def search():
    if request.method == 'POST':
        search_query = request.form.get('search_query')
        results = User.query.filter(User.username.ilike(f'%{search_query}%')).all()
        return render_template('search.html', results=results, user=current_user)
    return render_template('search.html', user=current_user)


@auth.route('/unfollow/<int:user_id>', methods=['POST'])
@login_required
def unfollow(user_id):
    user = User.query.get(user_id)
    if user is None:
        flash('User not found.')
        return None
    if user == current_user:
        flash('You cannot unfollow yourself.')
        return None
    current_user.unfollow(user)
    db.session.commit()
    flash('You have unfollowed {}.'.format(user.username))
    return redirect(url_for('auth.show_following', username=current_user.username))

@auth.route('/follow/<int:user_id>', methods=['POST'])
@login_required
def follow(user_id):
    user = User.query.get(user_id)
    if user is None:
        flash('User not found.')
        return None
    if user == current_user:
        flash('You cannot follow yourself.')
        return None
    current_user.follow(user)
    db.session.commit()
    flash('You have followed {}.'.format(user.username))
    return redirect(url_for('auth.show_following', username=user.username))



@auth.route('/profile/<username>')
@login_required
def profile(username):
    user = User.query.filter_by(username=username).first_or_404()
    answers = Answer.query.filter_by(user_id=user.id).all()
    len_answers = len(answers)
    questions = Question.query.filter_by(user_id=user.id).all()
    len_questions = len(questions)
    len_followers = user.followers.count()
    len_following = user.following.count()
    return render_template('profile-answers.html', user=user, len_answers=len_answers, len_questions=len_questions, len_followers=len_followers, len_following=len_following)


@auth.route('/profile/<username>/questions/<category>')
@login_required
def show_questions_category(username, category):
    user = User.query.filter_by(username=username).first_or_404()
    answers = Answer.query.filter_by(user_id=user.id).all()
    len_answers = len(answers)
    questions = Question.query.filter_by(user_id=user.id).all()
    len_questions = len(questions)
    len_followers = user.followers.count()
    len_following = user.following.count()
    category = Category.query.filter_by(name=category).first()
    category_id = category.id
    questions_category = Question.query.filter_by(user_id=user.id, category_id=category_id).all()
    return render_template('pro-que-category.html', user=user, category=category, questions=questions_category, len_questions=len_questions, len_followers=len_followers, len_following=len_following, len_answers=len_answers)


@auth.route('/profile/<username>/questions')
@login_required
def show_questions(username):
    user = User.query.filter_by(username=username).first_or_404()
    answers = Answer.query.filter_by(user_id=user.id).all()
    len_answers = len(answers)
    questions = Question.query.filter_by(user_id=user.id).all()
    len_questions = len(questions)
    len_followers = user.followers.count()
    len_following = user.following.count()
    return render_template('questions.html', user=user, len_questions=len_questions, len_followers=len_followers, len_following=len_following, questions=questions, len_answers=len_answers)


@auth.route('/profile/<username>/followers')
@login_required
def show_followers(username):
    user = User.query.filter_by(username=username).first_or_404()
    answers = Answer.query.filter_by(user_id=user.id).all()
    len_answers = len(answers)
    questions = Question.query.filter_by(user_id=user.id).all()
    len_questions = len(questions)
    len_followers = user.followers.count()
    len_following = user.following.count()
    followers = user.followers.all()
    return render_template('followers.html', user=user, followers=followers, len_questions=len_questions, len_followers=len_followers, len_following=len_following, len_answers=len_answers)

@auth.route('/profile/<username>/following')
@login_required
def show_following(username):
    user = User.query.filter_by(username=username).first_or_404()
    answers = Answer.query.filter_by(user_id=user.id).all()
    len_answers = len(answers)
    questions = Question.query.filter_by(user_id=user.id).all()
    len_questions = len(questions)
    len_followers = user.followers.count()
    len_following = user.following.count()
    following = user.following.all()
    return render_template('following.html', user=user, following=following, len_questions=len_questions, len_followers=len_followers, len_following=len_following, len_answers=len_answers)

website/views.py
from flask import Blueprint,render_template, request, flash, jsonify, redirect, url_for
from flask_login import login_required, current_user
from . import db
import json
from .models import Question, Category, Answer
from PIL import Image
from werkzeug.utils import secure_filename
import os

views = Blueprint('views', __name__)

# with open('path/to/image.png', 'rb') as f:
#     img_data = f.read()


@views.route('/', methods=['GET', 'POST'])
@login_required
def home():
    answers = Answer.query.all()
    return render_template('home.html', user=current_user, answers=answers)


@views.route('/answer', methods=['GET', 'POST'])
@login_required
def answer():
    questions = Question.query.all()
    
    return render_template('answer.html', user=current_user, questions=questions)


@views.route('/category', methods=['GET', 'POST'])
@login_required
def category():
    categories = Category.query.all()
    questions = Question.query.all()
    return render_template('category.html', user=current_user, questions=questions)

@views.route('/category/<category>', methods=['GET', 'POST'])
@login_required
def category_answers(category):
    category = Category.query.filter_by(name=category).first()
    category_id = category.id
    questions = Question.query.filter_by(category_id=category_id).all()
    return render_template('category.html', user=current_user, questions=questions)


@views.route('/profile/<username>/questions/<int:question_id>', methods=['DELETE'])
@login_required
def delete_question(username, question_id):
    question = Question.query.filter_by(id=question_id, user=current_user).first()
    if question:
        db.session.delete(question)
        db.session.commit()
        flash('Your question has been deleted!', 'success')
    return jsonify({'success': True})




@views.route('/create-question', methods=['GET', 'POST'])
@login_required
def create_question():
    if request.method == 'POST':
        question = request.form.get('question')
        category = request.form.get('category')

        if len(question) < 1:
            flash('Question is too short.', category='error')
        else:
            category = Category.query.filter_by(name=category).first()
            if category:
                category_id = category.id
                new_question = Question(question=question, category_id=category_id, user_id=current_user.id)
                db.session.add(new_question)
                db.session.commit()
                flash('Question created!', category='success')
                return redirect(url_for('auth.show_questions', username=current_user.username))
            else:
                flash('Category does not exist.', category='error')
        return redirect(url_for('auth.show_questions'))




ALLOWED_EXTENSIONS = {'png', 'jpg', 'jpeg', 'gif'}
def allowed_file(filename):
    return '.' in filename and filename.rsplit('.', 1)[1].lower() in ALLOWED_EXTENSIONS



@views.route('/<category>/<int:question_id>', methods=['GET', 'POST'])
@login_required
def question(category,question_id):
    question = Question.query.filter_by(id=question_id).first()
    category = Category.query.filter_by(name=category).first()
    from main import app
    if request.method == 'POST':

        answer = request.form.get('answer')
        file = request.files['photo']
        if file and allowed_file(file.filename):
            filename = secure_filename(file.filename)
            file.save(os.path.join(app.config['UPLOAD_FOLDER'], filename))
        else:
            filename = None
        question_id = question_id
        question = Question.query.filter_by(id=question_id).first()
        new_answer = Answer(answer=answer, question_id=question_id, user_id=current_user.id, photo=filename)
        db.session.add(new_answer)
        db.session.commit()
        flash('Answer created!', category='success')
        return render_template('question.html', user=current_user, question=question, category=category)

    return render_template('question.html', user=current_user, question=question, category=category)


@views.route('/following', methods=['GET', 'POST'])
@login_required
def following():
    following = current_user.following

    return render_template('following_page.html', user=current_user, following=following)

website/templates/base.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
        crossorigin="anonymous" />

        {% block head %}
        {% endblock %}

    <script src="{{ url_for('static', filename='script.js') }}"></script>
    <script>
        deleteQuestion();
      </script>
    
    <link rel="stylesheet" href="{{ url_for('static', filename='Profile.css') }}">

    <title>{% block title%}Home{% endblock%}</title>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-info bg-gradient">
        <div class="container-fluid">

            <div class="container" style="margin-left: 5%;">
                <a class="navbar-brand" id="home" href="/">Askmenow</a>
            </div>

            
            <div class="container" style="margin-left: 10px; ">
                <div class="collapse navbar-collapse" id="navbarSupportedContent">


                    <ul class="navbar-nav mr-auto">
                        {% if user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link font-weight-bold" href="{{ url_for('auth.profile', username=current_user.username) }}">Profile</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link font-weight-bold" href="/answer">Answer</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link font-weight-bold" href="/following">Following</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link font-weight-bold" href="/category">Category</a>
                        </li>
                        <li class="nav-item">
                            <button class="btn btn-primary my-2 my-sm-0" type="submit" onclick="openQuestionForm()"
                                >Add</button>
                        </li>
                        {% endif %}
                    </ul>

                    <div class="navbar-nav">
                        {% if user.is_authenticated %}
                        <a class="nav-item nav-link" id="logout" href="/logout">Logout</a>
                        {% else %}
                        <a class="nav-item nav-link" id="login" href="/login">Login</a>
                        <a class="nav-item nav-link" id="signup" href="/signup">Signup</a>
                        {% endif %}
                    </div>

                </div>
            </div>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="container-md">
                {% if user.is_authenticated %}
                
                <form action="{{ url_for('auth.search') }}" method="POST">
                    <div class="input-group">
                        <input type="text" class="form-control" name="search_query" placeholder="Search for users...">
                        <div class="input-group-append">
                            <button class="btn btn-primary my-2 my-sm-0" type="submit"><i
                                    class="fa fa-search"></i></button>
                        </div>
                    </div>
                </form>
                {% endif %}
            </div>




        </div>


    </nav>

    {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
    {% for category, message in messages %}
    {% if category == 'error' %}
    <div class="alert alert-danger alert-dismissable fade show" role="alert">
        {{ message }}
        <button type="button" class="close" data-dismiss="alert">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    {% else %}
    <div class="alert alert-success alert-dismissable fade show" role="alert">
        {{ message }}
        <button type="button" class="close" data-dismiss="alert">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    {% endif %}
    {% endfor %}
    {% endif %}
    {% endwith %}



    <div class="container justify-content-center">
        {% block content %}
        {% endblock %}
    </div>


    <!-- the pop up modal -->

    <div class="modal" tabindex="-1" role="dialog" id="questionForm">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Ask a Question</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <form action="{{ url_for('views.create_question') }}" method="POST">
                        <div class="form-group">
                            <label for="question">Question:</label>
                            <input type="text" class="form-control" id="question" name="question" required>
                        </div>
                        <div class="form-group">
                            <label for="category">Category:</label>
                            <select class="form-control" id="category" name="category" required>
                                <option value="Technology">Technology</option>
                                <option value="Sports">Sports</option>
                                <option value="Music">Music</option>
                                <!-- <option value="Sports">Sports</option> -->
                            </select>
                        </div>
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </form>
                </div>
            </div>
        </div>
    </div>





    <script>
        function openQuestionForm() {
            $('#questionForm').modal('show');
        }
    </script>







    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>


    {% block javascript %}
    
    {% endblock %}

</body>

</html>

website/templates/category.html
{% extends "base.html" %}

{% block title%}{{ category }}{% endblock%}

{% block content %}

<div class="col-sm-3">
    <div class="dropdown">
      <button class="btn btn-secondary dropdown-toggle" role="button" type="button" id="categoryDropdown"
        data-toggle="dropdown" aria-expanded="false" aria-haspopup="true">
        Select Category
      </button>
      <div class="dropdown-menu" aria-labelledby="categoryDropdown">
        <a class="dropdown-item" href="/category">all</a>
        <a class="dropdown-item" href="/category/Technology">Technology</a>
        <a class="dropdown-item" href="/category/Music">Music</a>
        <a class="dropdown-item" href="/category/Sports">Sports</a>
      </div>
    </div>
  </div>

{% for question in questions %}
{% for answer in question.answers %}

<div class="container">
    <div class="row">
        <div class="col-md-6 offset-md-3">
            <div class="card mt-2">
                {% if answer.photo %}
                <img src="{{ url_for('static', filename='images/' + answer.photo) }}" alt="Photo" class="card-img-top"
                    class="img-fluid">
                {% endif %}

                <div class="card-body">
                    <h5 class="card-title">{{ answer.question.question }}</h5>
                    <p class="card-text">{{ answer.answer }}</p>

                    <div class="card-footer">
                        <small class="text-muted">Posted by <a href="#">{{ answer.user.username }}</a></small>
                        <div class="float-right">
                            <a href="#" class="btn btn-sm btn-outline-secondary mr-2"><i class="fa fa-thumbs-up"></i>
                                Upvote</a>
                            <a href="#" class="btn btn-sm btn-outline-secondary mr-2"><i class="fa fa-thumbs-down"></i>
                            </a>
                            <a href="#" class="btn btn-sm btn-outline-secondary"><i class="fa fa-comment"></i>
                                Comment</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<br />

{% endfor %}
{% endfor %}


{% endblock %}

website/templates/followers.html
{% extends "profile.html" %}
{% block title%}{{ category }}{% endblock%}


{% block head %}

<style>
    .profile-card {
        cursor: pointer;
        transition: box-shadow 0.2s ease-in-out;
    }

    .profile-card:hover {
        box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2);
    }
</style>



{% endblock %}




{% block followers %}

{% for follower in followers %}
<div class="card mb-2 profile-card col-md-6 offset-md-3" style="max-width: 540px; background: none;">
    <div class="row no-gutters">
        <div class="col-md-3">
            <img src="11.jpeg" class="card-img" alt="..." style="border-radius: 50%;">
        </div>
        <div class="col-md-8">
            <div class="card-body">
                <h5 class="card-title">{{ follower.username }}</h5>
                <p class="card-text font-weight-lighter">{{ follower.followers.count() }} followers {{
                    follower.following.count() }} following </p>
                {% if follower != current_user %}
                {% if current_user in follower.followers %}
                <form action="{{ url_for('auth.unfollow', user_id=follower.id) }}" method="post">
                    <button type="submit" class="btn btn-primary">Unfollow</button>
                </form>
                {% else %}
                <form action="{{ url_for('auth.follow', user_id=follower.id) }}" method="post">
                    <button type="submit" class="btn btn-primary">Follow</button>
                </form>
                {% endif %}
                {% endif %}
            </div>
        </div>
    </div>
</div>
<br />
{% endfor %}


<script>
    const cards = document.querySelectorAll('.profile-card');
    cards.forEach(card => {
        card.addEventListener('click', () => {
            const username = card.querySelector('.card-title').textContent;
            window.location.href = `/profile/${username}`;
        });
    });
</script>

{% endblock %}

website/templates/following.html
{% extends "profile.html" %}
{% block title%}{{ category }}{% endblock%}

{% block head %}

<style>
    .profile-card {
        cursor: pointer;
        transition: box-shadow 0.2s ease-in-out;
    }

    .profile-card:hover {
        box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2);
    }
</style>



{% endblock %}



{% block following %}

{% for followed in following %}
<div class="card mb-2 profile-card col-md-6 offset-md-3" style="max-width: 540px; background: none;">
    <div class="row no-gutters">
        <div class="col-md-3">
            <img src="11.jpeg" class="card-img" alt="..." style="border-radius: 50%;">
        </div>
        <div class="col-md-8">
            <div class="card-body">
                <h5 class="card-title">{{ followed.username }}</h5>
                <p class="card-text font-weight-lighter">{{ followed.followers.count() }} followers {{
                    followed.following.count() }} following </p>
                {% if followed != current_user %}
                {% if current_user in followed.followers %}
                <form action="{{ url_for('auth.unfollow', user_id=followed.id) }}" method="post">
                    <button type="submit" class="btn btn-primary">Unfollow</button>
                </form>
                {% else %}
                <form action="{{ url_for('auth.follow', user_id=followed.id) }}" method="post">
                    <button type="submit" class="btn btn-primary">Follow</button>
                </form>
                {% endif %}
                {% endif %}
            </div>

        </div>
    </div>
</div>
<br />
{% endfor %}

<script>
    const cards = document.querySelectorAll('.profile-card');
    cards.forEach(card => {
        card.addEventListener('click', () => {
            const username = card.querySelector('.card-title').textContent;
            window.location.href = `/profile/${username}`;
        });
    });
</script>

{% endblock %}

website/templates/home.html
{% extends "base.html" %}
{% block title%}Home{% endblock%}
{% block content %}
<br />


{% for answer in answers %}

<div class="container">
    <div class="row">
        <div class="col-md-6 offset-md-3">
            <div class="card mt-2">


                <div class="card-body">
                    <h5 class="card-title">{{ answer.question.question }}</h5>
                    {% if answer.photo %}
                    <img src="{{ url_for('static', filename='images/' + answer.photo) }}" alt="Photo"
                        class="card-img-top" class="img-fluid">
                    {% endif %}
                    <p class="card-text">{{ answer.answer }}</p>

                    <div class="card-footer">
                        <small class="text-muted">Posted by <a href="#">{{ answer.user.username }}</a></small>
                        <div class="float-right">
                            <a href="#" class="btn btn-sm btn-outline-secondary mr-2"><i class="fa fa-thumbs-up"></i>
                                Upvote</a>
                            <a href="#" class="btn btn-sm btn-outline-secondary mr-2"><i class="fa fa-thumbs-down"></i>
                            </a>
                            <a href="#" class="btn btn-sm btn-outline-secondary"><i class="fa fa-comment"></i>
                                Comment</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<br />


{% endfor %}


{% endblock %}

website/templates/pro-que-category.html
{% extends "profile.html" %}
{% block title%}{{ category }}{% endblock%}
{% block questions %}


{% for question in questions %}
<div class="card w-75 col-md-6 offset-md-3">
    <div class="card-body">
        <h5 class="card-title">{{ question.question }}</h5>
        <p class="card-text">{{ question.answers|length }} answers.</p>
        <div class="d-flex justify-content-between">
            <form action="{{ url_for('views.question', category=question.category.name, question_id=question.id) }}" method="GET">
                <button class="btn btn-primary" type="submit">Answer</button>
            </form>
            {% if question.user == current_user %}
            <button onclick="deleteQuestion()" type="submit" class="btn btn-danger delete-question ml-2" data-questionid="{{ question.id }}" data-username="{{ question.user.username }}">
                <span aria-hidden="true">&times;</span>
            </button>
            {% endif %}
        </div>
        
    </div>
</div>
<br />
{% endfor %}





{% endblock %}

website/templates/questions.html
{% extends "profile.html" %}
{% block title%}{{ category }}{% endblock%}
{% block questions %}

{% for question in user.questions %}
<div class="card w-75 col-md-6 offset-md-3">
    <div class="card-body">
        <h5 class="card-title">{{ question.question }}</h5>
        <p class="card-text">{{ question.answers|length }} answers.</p>
        <div class="d-flex justify-content-between">
            <form action="{{ url_for('views.question', category=question.category.name, question_id=question.id) }}" method="GET">
                <button class="btn btn-primary" type="submit">Answer</button>
            </form>
            {% if question.user == current_user %}
            <button onclick="deleteQuestion()" type="submit" class="btn btn-danger delete-question ml-2" data-questionid="{{ question.id }}" data-username="{{ question.user.username }}">
                <span aria-hidden="true">&times;</span>
            </button>
            {% endif %}
        </div>
        
    </div>
</div>
<br />
{% endfor %}

{% endblock %}

website/templates/search.html
{% extends "base.html" %}
{% block title%}search{% endblock%}

{% block head %}

<style>
    .profile-card {
        cursor: pointer;
        transition: box-shadow 0.2s ease-in-out;
    }

    .profile-card:hover {
        box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2);
    }
</style>





{% endblock %}

{% block content %}
<br />

<div class="container">

    {% for result in results %}
    {% if current_user.id != result.id %}

    <div class="card mb-2  profile-card" style="max-width: 540px; background: none;">
        <div class="row no-gutters">
            <div class="col-md-3">
                <img src="11.jpeg" class="card-img" alt="..." style="border-radius: 50%;">
            </div>
            <div class="col-md-8">
                <div class="card-body">
                    <h5 class="card-title">{{ result.username }}</h5>
                    <p class="card-text font-weight-lighter">{{ result.followers.count() }} followers {{
                        result.following.count() }} following </p>
                        {% if current_user in result.followers %}
                        <form action="{{ url_for('auth.unfollow', user_id=result.id) }}" method="post">
                            <button type="submit" class="btn btn-primary">Unfollow</button>
                        </form>
                        {% else %}
                        <form action="{{ url_for('auth.follow', user_id=result.id) }}" method="post">
                            <button type="submit" class="btn btn-primary">Follow</button>
                        </form>
                        {% endif %}
                </div>
            </div>
            
            
            
        </div>
    </div>


    <br />

    {% endif %}
    {% endfor %}
</div>

<script>
    const cards = document.querySelectorAll('.profile-card');
    cards.forEach(card => {
        card.addEventListener('click', () => {
            const username = card.querySelector('.card-title').textContent;
            window.location.href = `/profile/${username}`;
        });
    });
</script>

{% endblock %}